package client;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextArea;

/**
 *
 * @author MyPC
 */
public class ClientFrame extends javax.swing.JFrame {

    private Client client;
    FileConnection fc;

    /**
     * Creates new form Client
     */
    public ClientFrame() {
        initComponents();
    }

    public ClientFrame(Client c) {
        client = c;
        initComponents();
        client.setConnections(this);
        addWindowListener(new WindowAdapter() {/*khi đóng client gửi chuỗi đến server*/
            @Override
            public void windowClosing(WindowEvent e) {
                client.tc.sendStringToServer("close$" + client.getUserName());
                client.fc.sendStringToServer("close$" + client.getUserName());
            }

        });

    }

    public void refreshListUser(String name) {
        listUser.append(name + "\n");
    }

    public void refreshComboUser(String name) {
        comboUser.addItem(name);
    }

    public String getSelectedItem() {
        return (String) comboUser.getModel().getSelectedItem();
    }

    public void setSelectedItem(String item) {
        comboUser.getModel().setSelectedItem((Object) item);
    }

    public void clearUser() {
        listUser.setText("");
        String choices[] = {"Everyone"};
        comboUser.setModel(new DefaultComboBoxModel(choices));
    }

    public JTextArea getChatBox() {
        return chatBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        comboUser = new javax.swing.JComboBox<>();
        fileButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        sendMessageBox = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(client.getUserName()
        );

        chatBox.setEditable(false);
        chatBox.setColumns(20);
        chatBox.setFont(new java.awt.Font(".VnAvant", 0, 18)); // NOI18N
        chatBox.setLineWrap(true);
        chatBox.setRows(5);
        chatBox.setWrapStyleWord(true);
        jScrollPane1.setViewportView(chatBox);

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Everyone" }));
        comboUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUserActionPerformed(evt);
            }
        });

        fileButton.setText("File");
        fileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileButtonMouseClicked(evt);
            }
        });
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        sendMessageBox.setColumns(20);
        sendMessageBox.setFont(new java.awt.Font(".VnArial", 0, 18)); // NOI18N
        sendMessageBox.setLineWrap(true);
        sendMessageBox.setRows(5);
        sendMessageBox.setWrapStyleWord(true);
        jScrollPane4.setViewportView(sendMessageBox);

        sendButton.setText("SEND");
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        listUser.setEditable(false);
        listUser.setColumns(20);
        listUser.setFont(new java.awt.Font(".VnTeknicalH", 0, 18)); // NOI18N
        listUser.setLineWrap(true);
        listUser.setRows(5);
        listUser.setWrapStyleWord(true);
        jScrollPane3.setViewportView(listUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileButton)
                            .addComponent(sendButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUserActionPerformed

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        // TODO add your handling code here:
        String text = sendMessageBox.getText();
        if (text.length() < 1) {
            sendMessageBox.setText("");
            sendMessageBox.setCaretPosition(0);
        } else {
            /*Gửi tin nhắn text*/
            String sender = client.getUserName();
            String recipient = getSelectedItem();
            /*Chuỗi có dạng: text$nguoigui@nguoinhan@tinnhan*/
            String msg = "text$" + sender + "@" + recipient + "@"
                    + "<" + sender + "> to <" + recipient + ">: " + text + "\n";
            client.tc.sendStringToServer(msg);
            /*thread text gửi đến textserver*/
            sendMessageBox.setText("");
            sendMessageBox.setCaretPosition(0);
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed

    }//GEN-LAST:event_fileButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void fileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileButtonMouseClicked
        // TODO add your handling code here:
        FileConnection fc = new FileConnection(this, client);

        Thread fileThread = new Thread(fc);
        fileThread.start();
//        String text = fc.fc.getSelectedFile().getName();
        File file = fc.fc.getSelectedFile();
        String text = file.getName();
        String sender = client.getUserName();
        String recipient = getSelectedItem();
        /*Chuỗi có dạng: file$nguoigui@nguoinhan@tinnhan*/
        String msg = "file$" + sender + "@" + recipient + "@"
                + "<" + sender + "> to <" + recipient + ">: " + text + "\n";
        sendMessageBox.append(text);

//        String msgFile = "file$" + sender + "@" + recipient + "@"
//                + "<" + sender + "> to <" + recipient + ">: " + file + "\n";
        fc.sendStringToServer(msg);
        fc.sendFileToServer(file);
    }//GEN-LAST:event_fileButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClientFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatBox;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JButton fileButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea listUser;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea sendMessageBox;
    // End of variables declaration//GEN-END:variables
}
